// Curated Process Work exercise library for Talvira.
// Adapted from training materials and exercises supplied by the product owner.
// Keep attribution visible in user-facing library views. Do not reproduce source handouts verbatim.

export type PracticeLibraryItem = {
  id: string;
  title_ru: string;
  author: string;
  source?: string;
  channels: string[];
  use_in: Array<'personal_practice' | 'edge_program' | 'resource_library'>;
  intensity: 'low' | 'moderate' | 'high';
  requires_live_facilitator?: boolean;
  contraindications?: string[];
  purpose: string;
  steps: string[];
};

export const PROCESS_PRACTICE_LIBRARY: PracticeLibraryItem[] = [
  { id:'body_tension_catharsis', title_ru:'Движение из телесного напряжения', author:'авторская/учебная практика, предоставлена Мариной', channels:['body','movement','emotion'], use_in:['personal_practice','edge_program','resource_library'], intensity:'moderate', purpose:'Исследовать напряжение как процесс и позволить телу найти собственное разряжающее движение.', steps:['Найти заметное напряжение и уточнить его форму, интенсивность и дыхательный паттерн.','Очень умеренно усилить ощущение и заметить чувства, образы, воспоминания или внутренние голоса.','Позволить телу перейти из замирания в подходящее движение.','Завершить в найденном приятном телесном качестве.'] },
  { id:'polarity_scales', title_ru:'Полярности и сущность между ними', author:'Clare Hill', channels:['conflict','body','essence'], use_in:['personal_practice','edge_program'], intensity:'moderate', purpose:'Почувствовать обе стороны полярности и найти более глубокое качество, из которого возникает напряжение между ними.', steps:['Назвать две стороны полярности и почувствовать качество каждой.','Найти телесную опору.','Дать двум сторонам отдельные места и почувствовать напряжение между ними.','Следовать переживанию к сущности, не превращая это в интеллектуальный анализ.','Проверить, как контакт с сущностью меняет отношение к обеим сторонам.'] },
  { id:'barrier_work', title_ru:'Работа с барьером', author:'Arnold Mindell', source:'The Shaman’s Body', channels:['edge','body','dream'], use_in:['personal_practice','edge_program'], intensity:'moderate', purpose:'Не ломать барьер, а использовать его собственное качество как вход в дальнейший процесс.', steps:['Определить, что именно сейчас мешает.','Не избавляться от барьера, а сознательно использовать его качество и посмотреть, куда оно ведёт.','При появлении союзника дать ему форму и голос.','Спросить, как его качество может поддержать следующий маленький шаг.'] },
  { id:'second_attention_unexpected', title_ru:'Охота за непредсказуемым', author:'Arnold Mindell', source:'The Shaman’s Body', channels:['flirt','dream','movement','sensory'], use_in:['personal_practice','edge_program'], intensity:'moderate', purpose:'Развить второе внимание к неожиданным микросигналам.', steps:['Кратко заметить привычную историю о себе.','Найти один непредсказуемый сигнал.','Удержать его во втором внимании через доступный канал.','Позволить сигналу развернуться.','Вернуться к повседневному вопросу и найти применение.'] },
  { id:'deep_wisdom_elder', title_ru:'Глубинная мудрость и старейшинство', author:'Process Work учебная практика', channels:['conflict','role','body','resource'], use_in:['personal_practice','edge_program','resource_library'], intensity:'low', purpose:'Получить доступ к качествам старейшинства через вдохновляющую фигуру.', steps:['Вспомнить ситуацию, где нужны лидерство или старейшинство.','Выбрать вдохновляющую фигуру и выделить качество.','Через позу, дыхание, голос и взгляд временно войти в эту фигуру.','Из новой позиции посмотреть на ситуацию.','Вернуться в собственную позицию и записать полезное.'] },
  { id:'ingrid_body_drawing', title_ru:'Телесное ощущение — рисунок — движение', author:'Ingrid Rose', channels:['body','visual','movement'], use_in:['personal_practice','edge_program'], intensity:'moderate', purpose:'Перевести телесный сигнал в образ и движение, чтобы выявить его качество.', steps:['Найти текущее телесное ощущение.','Немного усилить и быстро изобразить.','Выбрать элемент рисунка, который привлекает внимание.','Перевести его энергию в движение, звук или позу.','Спросить, где это качество полезно в жизни.'] },
  { id:'symptom_tone_overtone', title_ru:'Симптом, тон и обертон', author:'Arnold Mindell', source:'Сила безмолвия', channels:['body','sound','movement','dream'], use_in:['personal_practice','edge_program'], intensity:'moderate', purpose:'Исследовать симптом через движение и звук и дать двум звуковым мирам взаимодействовать.', steps:['Выбрать знакомый симптом и описать ощущение без медицинской интерпретации.','Найти движение и звук/тон.','Позволить им вызвать образ или историю.','Найти второй контрастный тон и отдельную историю.','Удерживать оба мира и дождаться нового качества без форсирования.','Найти способ напомнить телу это качество в повседневности.'] },
  { id:'inner_oppressor_energy', title_ru:'Энергия внутреннего угнетателя', author:'Process Work учебная практика', channels:['voice','movement','edge'], use_in:['personal_practice','edge_program'], intensity:'moderate', purpose:'Отделить содержание критического голоса от его энергии и исследовать полезное качество энергии.', steps:['Услышать конкретную фразу внутреннего угнетателя.','Выделить заряженное качество голоса и выразить движением.','Развернуть движение всем телом.','Спросить, где это качество нужно самому пользователю.'] },
  { id:'accusation_100', title_ru:'Обвинение на 100%', author:'Process Work учебная практика', channels:['conflict','role','projection'], use_in:['personal_practice','edge_program'], intensity:'moderate', purpose:'Исследовать проецируемое качество через безопасный ролевой эксперимент.', steps:['Выделить суть обвинения и роль.','Войти в роль как в эксперимент, не утверждая объективную правду обвинения.','Усилить качество и посмотреть из него на повседневную жизнь.','Найти полезное и выйти из роли.'] },
  { id:'flirt_unmanifest', title_ru:'Работа с флиртом', author:'Process Work учебная практика', channels:['flirt','sensory','movement'], use_in:['personal_practice','edge_program','resource_library'], intensity:'low', purpose:'Получить доступ к непроявленному через случайно привлекающий сигнал.', steps:['Сформулировать открытый вопрос.','Расфокусировать внимание и заметить, что первым привлекло чувство.','Телесно стать этим флиртом через позу, форму, движение или звук.','Сохранять двойное внимание.','Получить послание и проверить его применимость к вопросу.'] },
  { id:'conflict_one_percent_truth', title_ru:'Признать часть правды', author:'Clare Hill / Stefan Müller training materials', channels:['conflict','edge','movement'], use_in:['personal_practice','edge_program'], intensity:'moderate', purpose:'Найти минимальную правдивую часть критики и исследовать её качество без капитуляции перед обвинением.', steps:['Вспомнить не самый тяжёлый конфликт.','Проверить, есть ли небольшая правдивая часть; если нет — исследовать край на признание.','Представить влияние маленького признания на атмосферу.','Войти в суть признанного качества через движение или звук.','Спросить, как качество может изменить отношения.'] },
  { id:'relationship_sound_role', title_ru:'Отношения через позу, звук и роль', author:'Process Work учебная практика', channels:['conflict','role','sound','movement'], use_in:['personal_practice','edge_program'], intensity:'moderate', purpose:'Исследовать фигуру партнёра через телесную позицию, звучание и образ, не приписывая реальному человеку мотивы.', steps:['Вспомнить проблему и увидеть позу другого.','Временно войти в эту позу как эксперимент.','Выразить состояние через звук, ритм или движение.','Развернуть звук/движение в образ и получить послание от качества.','Выйти из роли и проверить изменение собственного взгляда.'] },
  { id:'inner_opponent', title_ru:'Внутренний оппонент', author:'Clare Hill', source:'Relationship Training, Moscow 2020', channels:['conflict','role','polarity'], use_in:['personal_practice','edge_program'], intensity:'moderate', purpose:'Развернуть две внутренние позиции и найти ценное содержание оппозиционной стороны.', steps:['Назвать две внутренние позиции.','Дать каждой отдельное место и полностью поддержать каждую.','При необходимости занять третью нейтральную позицию.','Продолжать до появления качества второй позиции, которое можно интегрировать.'] },
  { id:'high_dream_essence', title_ru:'Сущность высокого сна', author:'Clare Hill', source:'Relationship Training, Moscow 2020', channels:['relationship','body','movement','essence'], use_in:['personal_practice','edge_program'], intensity:'moderate', purpose:'Исследовать телесную сущность высокого сна и край на её проживание.', steps:['Сформулировать высокий сон и временно оставить конкретного партнёра за рамками.','Найти телесное ощущение, позу и движение.','Следовать движению к глубинному качеству.','Замечать убеждение, которое мешает владеть качеством.','Вернуть качество в реальные отношения и проверить собственное поведение.'] },
  { id:'wise_mind', title_ru:'Доступ к Мудрому уму', author:'Stefan Müller, Process Work Institute Zurich', source:'Работа с конфликтами в трудные времена, МИПОПП 2023', channels:['resource','body','imagery'], use_in:['resource_library','edge_program'], intensity:'low', purpose:'Найти собственный вход в более широкое сострадательное присутствие.', steps:['Найти физическую опору и заметить дыхание без требования его менять.','Выбрать естественный вход в ресурс: тело, природа, животное, значимая фигура, цвет или звук.','Отвлекающие или критические части признать и предложить им временно отойти.','Ненадолго побыть в более широком присутствии.'] },
  { id:'behind_mask', title_ru:'За маской', author:'Amy Mindell', channels:['dream','body','figure'], use_in:['resource_library','edge_program'], intensity:'low', purpose:'Коротко обнаружить тонкую фигуру или чувство, которое хочет проявиться сейчас.', steps:['Поместить ладонь перед лицом как условную маску.','Заметить тонкие чувства и микродвижения.','Спросить, какой опыт, чувство или фигура пытается проявиться.','Дать ей немного больше формы и услышать выражение.'] },
  { id:'ally_from_problem', title_ru:'Союзник внутри трудной силы', author:'Arnold Mindell', source:'The Shaman’s Body', channels:['body','dream','conflict','movement'], use_in:['personal_practice','edge_program'], intensity:'high', requires_live_facilitator:true, contraindications:['acute_crisis','high_unresolved_risk','recent_severe_trauma_activation'], purpose:'Исследовать трудную энергию как потенциального союзника при достаточной устойчивости и живой поддержке.', steps:['Отделить факты события от переживаемой энергии угрозы.','Исследовать образ/качество силы с достаточной дистанцией.','Войти в роль только при устойчивом состоянии.','Найти безопасное применение полезного качества.','Выйти из роли и переориентироваться.'] },
  { id:'trauma_spirit', title_ru:'Энергия духа трудного события', author:'Process Work учебная практика', channels:['trauma','dream','movement','landscape'], use_in:['edge_program'], intensity:'high', requires_live_facilitator:true, contraindications:['self_guided_only','acute_crisis','high_unresolved_risk'], purpose:'Работать с символической энергией трудного опыта без подробного повторного погружения.', steps:['Выбрать только достаточно стабильный материал.','Исследовать атмосферу и символическое качество без воспроизведения травмы.','Дать образ, имя, движение или звук.','Перевести качество в ландшафт и исследовать мудрость.','Вернуться к настоящему и найти безопасное применение.'] }
];

export function practiceLibraryForPrompt(channel: string) {
  const normalized = String(channel || '').toLowerCase();
  return PROCESS_PRACTICE_LIBRARY.filter((item) =>
    item.use_in.includes('personal_practice') && item.intensity !== 'high' &&
    (normalized === 'mixed' || !normalized || item.channels.includes(normalized))
  );
}
